head: cranectl
cluster:
  crane01:
    NodeAddr: 192.168.2.10/24
    HostNum: 64
    Offset: 1
    Subnet: 10.10.0.0/16
    SwitchNum: 1
  crane02:
    NodeAddr: 192.168.2.11/24
    HostNum: 64
    Offset: 65
    Subnet: 10.11.0.0/16
    SwitchNum: 1
  crane03:
    NodeAddr: 192.168.2.12/24
    HostNum: 64
    Offset: 129
    Subnet: 10.12.0.0/16
    SwitchNum: 1
  # cranectl:
  #   NodeAddr: 192.168.2.13/24
  #   HostNum: 20
  #   Offset: 1
  #   Subnet: 10.13.0.0/16
  #   SwitchNum: 1
  